import { useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import { createTranslationWeek, listTranslationWeeks, updateTranslationDay, updateTranslationWeek, type Session, type TranslationArticleDay, type TranslationArticleWeek } from "./api";

const plan = [
  { name: "Monday", time: "6:15–7:15 AM · 5:00–6:00 PM", focus: "Listen to Mahant Swami’s video; read one page and capture three ideas.", checks: [["listenedDone", "Listened / re-listened"], ["notesCaptured", "Notes captured"], ["readingDone", "Reading done"]] },
  { name: "Tuesday", time: "6:15–7:15 AM · 5:00–6:00 PM", focus: "Continue or re-listen for clarity; read one page and develop the opening image.", checks: [["listenedDone", "Listened / re-listened"], ["notesCaptured", "Notes captured"], ["readingDone", "Reading done"]] },
  { name: "Wednesday", time: "6:15–7:15 AM · 5:00–6:00 PM · 6:30–7:45 PM", focus: "Choose three central ideas; write only the opening paragraph in the extended session.", checks: [["notesCaptured", "Listening / notes done"], ["readingDone", "Reading done"], ["writingDone", "Writing done"]] },
  { name: "Thursday", time: "6:15–7:15 AM · 5:00–6:00 PM", focus: "Read one page; review Wednesday’s opening and mentally structure the body.", checks: [["listenedDone", "Listened / re-listened"], ["notesCaptured", "Notes captured"], ["readingDone", "Reading done"]] },
  { name: "Friday", time: "6:15–7:15 AM · 5:00–6:00 PM · 6:30–7:45 PM", focus: "Read one page; write two to three body paragraphs from your notes.", checks: [["notesCaptured", "Listening / notes done"], ["readingDone", "Reading done"], ["writingDone", "Writing done"]] },
  { name: "Saturday", time: "6:15–7:15 AM · 6:30–7:45 PM", focus: "Read one page; write the closing and read the full draft aloud once.", checks: [["notesCaptured", "Listening / notes done"], ["readingDone", "Reading done"], ["writingDone", "Writing done"]] },
  { name: "Sunday", time: "Full day · 5+ hours", focus: "Deep reading, final revision, submit or archive; revise the next plan and attend satsang if possible.", checks: [["deepReadingDone", "Deep reading done"], ["articleFinalised", "Article finalised"], ["submitted", "Submitted"]] },
] as const;

const stages = [["openingDone", "Opening paragraph"], ["bodyOneTwoDone", "Body para 1–2"], ["bodyThreeDone", "Body para 3"], ["closingDone", "Closing"], ["readAloudDone", "Full draft read aloud"], ["finalRevisionDone", "Final revision"], ["submittedArchived", "Submitted / archived"]] as const;
const monday = () => { const date = new Date(); const shift = (date.getDay() + 6) % 7; date.setDate(date.getDate() - shift); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 10); };
const listOf = (raw: string) => { try { const value = JSON.parse(raw); return Array.isArray(value) ? value : []; } catch { return []; } };

export function TranslationArticleTracker({ session }: { session: Session }) {
  const [weeks, setWeeks] = useState<TranslationArticleWeek[]>([]); const [selected, setSelected] = useState("");
  const [weekStart, setWeekStart] = useState(monday); const [topic, setTopic] = useState(""); const [notice, setNotice] = useState("");
  const reviewer = ["SUPER_ADMIN", "ADMIN"].includes(session.user.role) && session.user.team !== "TRANSLATION";
  const reload = () => listTranslationWeeks(session.token).then((items) => { setWeeks(items); setSelected((current) => current && items.some((week) => week.id === current) ? current : items[0]?.id ?? ""); }).catch((e: unknown) => setNotice(e instanceof Error ? e.message : "Could not load the article tracker"));
  useEffect(() => { void reload(); }, [session.token]);
  const week = useMemo(() => weeks.find((item) => item.id === selected) ?? null, [weeks, selected]);
  const saveWeek = async (data: Parameters<typeof updateTranslationWeek>[2]) => { if (!week) return; try { await updateTranslationWeek(session.token, week.id, data); setNotice("Weekly tracker saved."); reload(); } catch (e) { setNotice(e instanceof Error ? e.message : "Could not save the weekly tracker"); } };
  const saveDay = async (day: TranslationArticleDay, data: Parameters<typeof updateTranslationDay>[3]) => { if (!week) return; try { await updateTranslationDay(session.token, week.id, day.id, data); setNotice("Daily record saved."); reload(); } catch (e) { setNotice(e instanceof Error ? e.message : "Could not save the daily record"); } };
  const begin = async (event: FormEvent) => { event.preventDefault(); try { const made = await createTranslationWeek(session.token, { weekStart, ...(topic.trim() ? { topic: topic.trim() } : {}) }); setWeeks((items) => [made, ...items]); setSelected(made.id); setTopic(""); setNotice("Weekly article tracker started."); } catch (e) { setNotice(e instanceof Error ? e.message : "Could not start this week"); } };
  return <section className="article-tracker"><header className="article-heading"><div><span className="eyebrow">SATVIDYA MAGAZINE · 1 ARTICLE / WEEK</span><h1>{reviewer ? "Translation article tracker" : "Weekly article tracker"}</h1><p>{reviewer ? "Review-only view of each translator’s real weekly plan." : "Your weekly listening, reading and writing rhythm."}</p></div>{weeks.length > 0 && <select value={selected} onChange={(e) => setSelected(e.target.value)} aria-label="Choose article week">{weeks.map((item) => <option key={item.id} value={item.id}>{new Date(item.weekStart).toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" })}{reviewer ? ` · ${item.owner.displayName}` : ""}</option>)}</select>}</header>
    {notice && <p className="notice" role="status">{notice}</p>}
    {!reviewer && <form className="article-start" onSubmit={begin}><label>Week starts Monday<input type="date" value={weekStart} onChange={(e) => setWeekStart(e.target.value)} required /></label><label>Video / preaching topic <input value={topic} onChange={(e) => setTopic(e.target.value)} placeholder="Optional for now" /></label><button>Start this week</button></form>}
    {!week ? <ArticleScheduleTemplate reviewer={reviewer} /> : <><section className="article-meta"><label>Topic<input disabled={reviewer} defaultValue={week.topic ?? ""} onBlur={(e) => void saveWeek({ topic: e.target.value.trim() || null })} placeholder="Video or preaching topic" /></label><div className="reading-list"><strong>Reading list</strong>{[0, 1, 2, 3].map((index) => <input key={index} disabled={reviewer} defaultValue={listOf(week.readingList)[index] ?? ""} placeholder={`Reading ${index + 1}`} onBlur={(e) => { const next = listOf(week.readingList); next[index] = e.target.value.trim(); void saveWeek({ readingList: next.filter(Boolean) }); }} />)}</div></section>
      <section className="article-progress"><strong>Article progress</strong><div>{stages.map(([key, label]) => <label key={key} className={week[key] ? "is-done" : ""}><input type="checkbox" disabled={reviewer} checked={week[key]} onChange={(e) => void saveWeek({ [key]: e.target.checked })} />{label}</label>)}</div></section>
      <div className="article-days">{plan.map((item, index) => { const day = week.days.find((entry) => entry.weekday === index + 1); if (!day) return null; return <details key={day.id} className="article-day" open={index === 0}><summary><span><strong>{item.name}</strong><small>{item.time}</small></span><span>{item.focus}</span></summary><div className="article-day-body"><p>{item.focus}</p><div className="article-log"><label>What I did<textarea disabled={reviewer} defaultValue={day.whatDid ?? ""} onBlur={(e) => void saveDay(day, { whatDid: e.target.value.trim() || null })} /></label><label>What’s next<textarea disabled={reviewer} defaultValue={day.whatsNext ?? ""} onBlur={(e) => void saveDay(day, { whatsNext: e.target.value.trim() || null })} /></label><label>{index === 2 || index >= 4 ? "Writing progress" : "Reading done"}<textarea disabled={reviewer} defaultValue={(index === 2 || index >= 4 ? day.writingProgress : day.readingProgress) ?? ""} onBlur={(e) => void saveDay(day, index === 2 || index >= 4 ? { writingProgress: e.target.value.trim() || null } : { readingProgress: e.target.value.trim() || null })} /></label></div><div className="article-checks">{item.checks.map(([key, label]) => <label key={key} className={day[key] ? "is-done" : ""}><input type="checkbox" disabled={reviewer} checked={day[key]} onChange={(e) => void saveDay(day, { [key]: e.target.checked })} />{label}</label>)}</div></div></details>; })}</div>
    </>}</section>;
}

/** The actual supplied schedule is always visible. Starting a week turns this
 * exact layout into the translator's editable record; it is never guessed. */
function ArticleScheduleTemplate({ reviewer }: { reviewer: boolean }) {
  return <section className="article-plan-overview" aria-label="Weekly article plan">
    <header><div><strong>This week’s article plan</strong><p>{reviewer ? "A translator starts a week here. You can then review their real progress." : "Choose the Monday and topic above, then start the week. Your daily notes and checks open only after that."}</p></div><span>1 article · 7 days</span></header>
    <div className="article-plan-days">{plan.map((item) => <details key={item.name}><summary><span><strong>{item.name}</strong><small>{item.time}</small></span><span>{item.focus}</span></summary><p>{item.focus}</p></details>)}</div>
    <footer><strong>Progress appears after the week starts</strong><span>{stages.map(([, label]) => label).join(" · ")}</span></footer>
  </section>;
}
